{
  "hash": "ed35142b9fae9f35588d1bac3b301656",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Pronóstico de precipitación horaria en el aeropuerto JFK\"\nsubtitle: \"Modelo calibrado de dos etapas con validación temporal\"\nauthor: \"Miguelangel Palma Rojas\"\ndate: last-modified\nlang: es\n---\n\n## Objetivo\n\nLa precipitación horaria contiene muchos ceros: la mayoría de observaciones son secas y unas pocas tormentas concentran los mayores errores. Este notebook separa el problema en dos preguntas: **¿lloverá?** y, si llueve, **¿cuánto?**\n\nCada transformación, modelo y evaluación aparece en el propio notebook. El pronóstico usa las mediciones meteorológicas actuales y la precipitación observada anteriormente; nunca usa información futura.\n\n## Paquetes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(here)\nlibrary(knitr)\nstopifnot(requireNamespace(\"xgboost\", quietly = TRUE))\n```\n:::\n\n\n## Leer el snapshot reproducible\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweather <- read_csv(\n  here(\"data\", \"jfk_weather_snapshot.csv\"),\n  show_col_types = FALSE,\n  col_types = cols(date = col_datetime())\n) |>\n  arrange(date)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrequired_columns <- c(\n  \"date\", \"humidity\", \"temperature_f\", \"station_pressure\",\n  \"wind_speed_mph\", \"precipitation_in\"\n)\n\nstopifnot(\n  all(required_columns %in% names(weather)),\n  anyDuplicated(weather$date) == 0,\n  !any(weather$precipitation_in < 0, na.rm = TRUE)\n)\n```\n:::\n\n\n## Crear variables disponibles al predecir\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweather <- weather |>\n  mutate(\n    rain = factor(if_else(precipitation_in > 0, \"rain\", \"dry\"),\n      levels = c(\"rain\", \"dry\")),\n    precipitation_lag1 = lag(precipitation_in, default = 0),\n    rain_lag1 = lag(as.integer(precipitation_in > 0), default = 0),\n    gap_hours = as.numeric(difftime(date, lag(date), units = \"hours\")),\n    gap_hours = replace_na(gap_hours, median(gap_hours, na.rm = TRUE)),\n    month_sin = sin(2 * pi * month(date) / 12),\n    month_cos = cos(2 * pi * month(date) / 12),\n    hour_sin = sin(2 * pi * hour(date) / 24),\n    hour_cos = cos(2 * pi * hour(date) / 24)\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweather |>\n  summarise(\n    observaciones = n(),\n    primera_observacion = min(date),\n    ultima_observacion = max(date),\n    horas_lluviosas = sum(rain == \"rain\"),\n    proporcion_lluviosa = mean(rain == \"rain\")\n  ) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n| observaciones|primera_observacion |ultima_observacion  | horas_lluviosas| proporcion_lluviosa|\n|-------------:|:-------------------|:-------------------|---------------:|-------------------:|\n|          4067|2010-01-01 04:51:00 |2018-07-26 10:51:00 |             393|               0.097|\n\n\n:::\n:::\n\n\n## Explorar el objetivo\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(weather, aes(x = precipitation_in)) +\n  geom_histogram(binwidth = 0.01, boundary = 0,\n    fill = \"#2A9D8F\", color = \"white\") +\n  coord_cartesian(xlim = c(0, quantile(weather$precipitation_in, 0.995))) +\n  labs(\n    title = \"La precipitación horaria contiene muchos ceros\",\n    x = \"Precipitación (pulgadas)\", y = \"Observaciones\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(plot.title = element_text(face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/precipitation-distribution-1.png){fig-alt='Histograma que muestra que la mayoría de las observaciones de precipitación son cero.' width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweather |>\n  mutate(day = as.Date(date)) |>\n  group_by(day) |>\n  summarise(precipitation_in = sum(precipitation_in), .groups = \"drop\") |>\n  ggplot(aes(x = day, y = precipitation_in)) +\n  geom_col(fill = \"#457B9D\", width = 1) +\n  labs(\n    title = \"La lluvia llega en episodios breves e irregulares\",\n    x = \"Fecha\", y = \"Precipitación diaria (pulgadas)\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(plot.title = element_text(face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/daily-series-1.png){fig-alt='Totales diarios de precipitación en JFK a través del tiempo.' width=672}\n:::\n:::\n\n\n## Conservar el orden temporal\n\nEl primer 70% selecciona los modelos, el siguiente 10% los calibra y el 20% más reciente se usa una sola vez para la evaluación final.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nfinal_split <- initial_time_split(weather, prop = 0.8)\ndevelopment_data <- training(final_split)\ntesting_data <- testing(final_split)\n\nvalidation_split <- initial_time_split(development_data, prop = 0.875)\nmodeling_data <- training(validation_split)\nvalidation_data <- testing(validation_split)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbind_rows(\n  modeling_data |> summarise(particion = \"Modelado\", n = n(), inicio = min(date), fin = max(date)),\n  validation_data |> summarise(particion = \"Calibración\", n = n(), inicio = min(date), fin = max(date)),\n  testing_data |> summarise(particion = \"Prueba final\", n = n(), inicio = min(date), fin = max(date))\n) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|particion          |    n|inicio              |fin                 |\n|:------------------|----:|:-------------------|:-------------------|\n|Modelado           | 2846|2010-01-01 04:51:00 |2015-12-13 09:51:00 |\n|Calibraci<U+00F3>n |  407|2015-12-14 04:51:00 |2016-11-05 18:51:00 |\n|Prueba final       |  814|2016-11-05 22:51:00 |2018-07-26 10:51:00 |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass_resamples <- rolling_origin(\n  modeling_data,\n  initial = 1500,\n  assess = 325,\n  cumulative = TRUE,\n  skip = 324\n)\n\nclass_resamples\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Rolling origin forecast resampling \n# A tibble: 4 x 2\n  splits             id    \n  <list>             <chr> \n1 <split [1500/325]> Slice1\n2 <split [1825/325]> Slice2\n3 <split [2150/325]> Slice3\n4 <split [2475/325]> Slice4\n```\n\n\n:::\n:::\n\n\n## Líneas base\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbaseline_mean <- mean(development_data$precipitation_in)\n\nbaseline_predictions <- testing_data |>\n  transmute(\n    date, precipitation_in,\n    `Línea base seca` = 0,\n    `Media histórica` = baseline_mean\n  )\n```\n:::\n\n\n### Referencia anterior de una sola etapa\n\n\n::: {.cell}\n\n```{.r .cell-code}\npolynomial_recipe <- recipe(\n  precipitation_in ~ humidity + temperature_f +\n    station_pressure + wind_speed_mph,\n  data = development_data\n) |>\n  step_impute_median(all_numeric_predictors()) |>\n  step_normalize(all_numeric_predictors()) |>\n  step_poly(all_numeric_predictors(), degree = 2)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npolynomial_fit <- workflow() |>\n  add_recipe(polynomial_recipe) |>\n  add_model(linear_reg() |> set_engine(\"lm\")) |>\n  fit(data = development_data)\n\npolynomial_predictions <- predict(polynomial_fit, testing_data) |>\n  pull(.pred)\n```\n:::\n\n\n## Etapa 1: ocurrencia de lluvia\n\n### Receta de clasificación\n\n\n::: {.cell}\n\n```{.r .cell-code}\noccurrence_recipe <- recipe(\n  rain ~ humidity + temperature_f + station_pressure + wind_speed_mph +\n    precipitation_lag1 + rain_lag1 + gap_hours + month_sin + month_cos +\n    hour_sin + hour_cos,\n  data = modeling_data\n) |>\n  step_impute_median(all_numeric_predictors())\n```\n:::\n\n\n### Modelo de clasificación\n\n\n::: {.cell}\n\n```{.r .cell-code}\noccurrence_spec <- boost_tree(\n  trees = 600,\n  tree_depth = tune(),\n  min_n = tune(),\n  learn_rate = tune(),\n  loss_reduction = tune(),\n  sample_size = tune(),\n  mtry = tune()\n) |>\n  set_mode(\"classification\") |>\n  set_engine(\"xgboost\")\n```\n:::\n\n\n### Cuadrícula de clasificación\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredictor_names <- c(\n  \"humidity\", \"temperature_f\", \"station_pressure\", \"wind_speed_mph\",\n  \"precipitation_lag1\", \"rain_lag1\", \"gap_hours\", \"month_sin\",\n  \"month_cos\", \"hour_sin\", \"hour_cos\"\n)\n\noccurrence_grid <- grid_space_filling(\n  tree_depth(c(2L, 7L)), min_n(c(5L, 35L)), learn_rate(c(-3, -0.7)),\n  loss_reduction(), sample_prop(c(0.65, 1)),\n  finalize(mtry(), modeling_data |> select(all_of(predictor_names))),\n  size = 12\n)\n```\n:::\n\n\n### Ajuste temporal\n\n\n::: {.cell}\n\n```{.r .cell-code}\noccurrence_results <- workflow() |>\n  add_recipe(occurrence_recipe) |>\n  add_model(occurrence_spec) |>\n  tune_grid(\n    resamples = class_resamples,\n    grid = occurrence_grid,\n    metrics = metric_set(pr_auc, roc_auc, mn_log_loss)\n  )\n\nbest_occurrence <- select_best(occurrence_results, metric = \"pr_auc\")\nbest_occurrence |> kable(digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n| mtry| min_n| tree_depth| learn_rate| loss_reduction| sample_size|.config          |\n|----:|-----:|----------:|----------:|--------------:|-----------:|:----------------|\n|   11|    26|          5|     0.0069|         0.2565|      0.9682|pre0_mod12_post0 |\n\n\n:::\n:::\n\n\n### Entrenar el clasificador elegido\n\n\n::: {.cell}\n\n```{.r .cell-code}\noccurrence_workflow <- workflow() |>\n  add_recipe(occurrence_recipe) |>\n  add_model(occurrence_spec) |>\n  finalize_workflow(best_occurrence)\n\noccurrence_fit <- occurrence_workflow |>\n  fit(data = modeling_data)\n```\n:::\n\n\n## Etapa 2: cantidad de precipitación\n\nEl modelo de cantidad solo ve observaciones lluviosas. Así, miles de horas secas no ocultan la señal del tamaño de las tormentas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwet_modeling_data <- modeling_data |>\n  filter(rain == \"rain\")\n\namount_resamples <- rolling_origin(\n  wet_modeling_data,\n  initial = 140,\n  assess = 40,\n  cumulative = TRUE,\n  skip = 39\n)\n```\n:::\n\n\n### Receta de cantidad\n\n\n::: {.cell}\n\n```{.r .cell-code}\namount_recipe <- recipe(\n  precipitation_in ~ humidity + temperature_f + station_pressure +\n    wind_speed_mph + precipitation_lag1 + rain_lag1 + gap_hours +\n    month_sin + month_cos + hour_sin + hour_cos,\n  data = wet_modeling_data\n) |>\n  step_impute_median(all_numeric_predictors())\n```\n:::\n\n\n### Modelo de cantidad\n\n\n::: {.cell}\n\n```{.r .cell-code}\namount_spec <- boost_tree(\n  trees = 600,\n  tree_depth = tune(),\n  min_n = tune(),\n  learn_rate = tune(),\n  loss_reduction = tune(),\n  sample_size = tune(),\n  mtry = tune()\n) |>\n  set_mode(\"regression\") |>\n  set_engine(\"xgboost\")\n```\n:::\n\n\n### Cuadrícula y ajuste de cantidad\n\n\n::: {.cell}\n\n```{.r .cell-code}\namount_grid <- grid_space_filling(\n  tree_depth(c(2L, 6L)), min_n(c(3L, 25L)), learn_rate(c(-3, -0.7)),\n  loss_reduction(), sample_prop(c(0.65, 1)),\n  finalize(mtry(), wet_modeling_data |> select(all_of(predictor_names))),\n  size = 12\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\namount_results <- workflow() |>\n  add_recipe(amount_recipe) |>\n  add_model(amount_spec) |>\n  tune_grid(\n    resamples = amount_resamples,\n    grid = amount_grid,\n    metrics = metric_set(rmse, mae)\n  )\n\nbest_amount <- select_best(amount_results, metric = \"rmse\")\nbest_amount |> kable(digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n| mtry| min_n| tree_depth| learn_rate| loss_reduction| sample_size|.config          |\n|----:|-----:|----------:|----------:|--------------:|-----------:|:----------------|\n|    2|    25|          6|     0.0042|          2e-04|      0.7773|pre0_mod03_post0 |\n\n\n:::\n:::\n\n\n### Entrenar el modelo de cantidad\n\n\n::: {.cell}\n\n```{.r .cell-code}\namount_workflow <- workflow() |>\n  add_recipe(amount_recipe) |>\n  add_model(amount_spec) |>\n  finalize_workflow(best_amount)\n\namount_fit <- amount_workflow |>\n  fit(data = wet_modeling_data)\n```\n:::\n\n\n## Calibrar sin tocar la prueba final\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvalidation_predictions <- validation_data |>\n  select(date, rain, precipitation_in) |>\n  bind_cols(predict(occurrence_fit, validation_data, type = \"prob\")) |>\n  bind_cols(predict(amount_fit, validation_data)) |>\n  rename(amount_raw = .pred) |>\n  mutate(\n    amount_raw = pmax(amount_raw, 0),\n    logit_probability = qlogis(pmin(pmax(.pred_rain, 0.001), 0.999))\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprobability_calibration <- glm(\n  I(rain == \"rain\") ~ logit_probability,\n  data = validation_predictions,\n  family = binomial()\n)\n\nvalidation_predictions <- validation_predictions |>\n  mutate(rain_probability = predict(\n    probability_calibration, newdata = validation_predictions,\n    type = \"response\"\n  ))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\namount_scale <- validation_predictions |>\n  filter(rain == \"rain\") |>\n  summarise(scale = sum(precipitation_in * amount_raw) / sum(amount_raw^2)) |>\n  pull(scale)\n\namount_scale\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8347213\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthreshold_results <- crossing(\n  threshold = seq(0.05, 0.60, by = 0.01),\n  validation_predictions\n) |>\n  mutate(.pred = if_else(\n    rain_probability >= threshold, amount_raw * amount_scale, 0\n  )) |>\n  group_by(threshold) |>\n  summarise(rmse = sqrt(mean((precipitation_in - .pred)^2)), .groups = \"drop\")\n\nbest_threshold <- threshold_results |>\n  slice_min(rmse, n = 1, with_ties = FALSE) |>\n  pull(threshold)\n```\n:::\n\n\n## Reentrenar con todo el periodo de desarrollo\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfinal_occurrence_fit <- occurrence_workflow |>\n  fit(data = development_data)\n\nfinal_amount_fit <- amount_workflow |>\n  fit(data = development_data |> filter(rain == \"rain\"))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nholdout_predictions <- testing_data |>\n  select(date, rain, precipitation_in) |>\n  bind_cols(predict(final_occurrence_fit, testing_data, type = \"prob\")) |>\n  bind_cols(predict(final_amount_fit, testing_data)) |>\n  rename(amount_raw = .pred) |>\n  mutate(\n    amount_raw = pmax(amount_raw, 0),\n    logit_probability = qlogis(pmin(pmax(.pred_rain, 0.001), 0.999)),\n    rain_probability = predict(probability_calibration,\n      newdata = pick(everything()), type = \"response\"),\n    amount = amount_raw * amount_scale\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nholdout_predictions <- holdout_predictions |>\n  mutate(\n    `Modelo de dos etapas` = if_else(\n      rain_probability >= best_threshold, amount, 0\n    ),\n    `Precipitación esperada` = rain_probability * amount,\n    `Regresión polinómica` = polynomial_predictions,\n    `Línea base seca` = 0,\n    `Media histórica` = baseline_mean\n  )\n```\n:::\n\n\n## Rendimiento en la prueba final\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregression_metrics <- holdout_predictions |>\n  select(precipitation_in, `Línea base seca`, `Media histórica`,\n    `Regresión polinómica`, `Modelo de dos etapas`,\n    `Precipitación esperada`) |>\n  pivot_longer(-precipitation_in, names_to = \"modelo\", values_to = \".pred\") |>\n  group_by(modelo) |>\n  summarise(\n    rmse = sqrt(mean((precipitation_in - .pred)^2)),\n    mae = mean(abs(precipitation_in - .pred)),\n    rmse_lluvia = sqrt(mean((precipitation_in[precipitation_in > 0] -\n      .pred[precipitation_in > 0])^2)),\n    .groups = \"drop\"\n  ) |>\n  arrange(rmse)\n\nregression_metrics |> kable(digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|modelo                             |   rmse|    mae| rmse_lluvia|\n|:----------------------------------|------:|------:|-----------:|\n|Precipitaci<U+00F3>n esperada      | 0.0430| 0.0098|      0.1318|\n|Modelo de dos etapas               | 0.0439| 0.0091|      0.1305|\n|Regresi<U+00F3>n polin<U+00F3>mica | 0.0444| 0.0146|      0.1345|\n|Media hist<U+00F3>rica             | 0.0458| 0.0120|      0.1449|\n|L<U+00ED>nea base seca             | 0.0463| 0.0068|      0.1478|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\noccurrence_metrics <- holdout_predictions |>\n  summarise(\n    pr_auc = pr_auc_vec(rain, rain_probability, event_level = \"first\"),\n    roc_auc = roc_auc_vec(rain, rain_probability, event_level = \"first\"),\n    brier = brier_class_vec(rain, rain_probability, event_level = \"first\")\n  )\n\noccurrence_metrics |> kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n| pr_auc| roc_auc| brier|\n|------:|-------:|-----:|\n|  0.564|   0.918| 0.064|\n\n\n:::\n:::\n\n\n## Inspeccionar las predicciones\n\n\n::: {.cell}\n\n```{.r .cell-code}\nholdout_daily <- holdout_predictions |>\n  mutate(day = as.Date(date)) |>\n  group_by(day) |>\n  summarise(\n    Observada = sum(precipitation_in),\n    Predicha = sum(`Precipitación esperada`),\n    .groups = \"drop\"\n  ) |>\n  pivot_longer(c(Observada, Predicha), names_to = \"serie\", values_to = \"pulgadas\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(holdout_daily, aes(x = day, y = pulgadas, color = serie)) +\n  geom_line(linewidth = 0.8) +\n  scale_color_manual(values = c(Observada = \"#264653\", Predicha = \"#E76F51\")) +\n  labs(\n    title = \"Precipitación observada y predicha - prueba final\",\n    x = \"Fecha\", y = \"Precipitación diaria (pulgadas)\", color = NULL\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(plot.title = element_text(face = \"bold\"), legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/holdout-series-1.png){fig-alt='Precipitación diaria observada y predicha en el periodo final.' width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nholdout_predictions |>\n  mutate(grupo_probabilidad = ntile(rain_probability, 10)) |>\n  group_by(grupo_probabilidad) |>\n  summarise(\n    predicha = mean(rain_probability),\n    observada = mean(rain == \"rain\"),\n    .groups = \"drop\"\n  ) |>\n  ggplot(aes(x = predicha, y = observada)) +\n  geom_abline(slope = 1, intercept = 0, color = \"#777777\") +\n  geom_point(size = 2.5, color = \"#2A9D8F\") +\n  labs(title = \"Probabilidades de lluvia calibradas\", x = \"Predicha\", y = \"Observada\") +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/calibration-plot-1.png){fig-alt='Calibración de la probabilidad de lluvia por decil.' width=672}\n:::\n:::\n\n\n## Conclusión\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbest_model <- regression_metrics |> slice_min(rmse, n = 1)\nmean_baseline_rmse <- regression_metrics |>\n  filter(modelo == \"Media histórica\") |>\n  pull(rmse)\nrmse_improvement <- 100 * (mean_baseline_rmse - best_model$rmse) /\n  mean_baseline_rmse\n```\n:::\n\n\n- La mejor predicción final es **Precipitación esperada**, con RMSE **0.0430** y una reducción de **%** frente a la media histórica.\n- El modelo de ocurrencia alcanza PR AUC **0.564** y ROC AUC **0.918** en el periodo final intacto.\n- El umbral (**0.48**) y la corrección de cantidad (**0.83**) se aprendieron con el 10% intermedio, no con la prueba final.\n- El resultado es reproducible y evita fuga temporal, pero no pretende ser un *nowcast* operativo: para eso se necesitarían radar, nubosidad e historia horaria más densa.\n\nConsulta la [versión en inglés](../index.qmd).\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}